backtesting:
  start_date: 2017-01-01
  end_date: 2023-12-31

tickers:
  - AAPL
  - MSFT
  - GOOGL
  - NTFLX


alpaca:
  api_key: PK7E9XJMOBKCCSO6QRO0
  secret_key: BRHdnAeulXkhsV2MpbO6U9G5gtMJ5eETPBVEHlvd